language: node_js
node_js: --lts
before_script:
  - git config user.name Akiicat
  - git config user.email aaaa1379@gmail.com
  - sed -i'' "s~https://github.com/akiicat/akiicat.github.io.git~https://${GITHUB_ACCESS_TOKEN}@github.com/akiicat/akiicat.github.io.git~" _config.yml
script:
  - hexo g
  - hexo d
