# # # # # # # #
#   Akiicat   #
# # # # # # # #

# bundle
exclude: ['Gemfile', 'Gemfile.lock', 'vendor']

# Basic
name:               "Akiicat"
post_dir:           "articles"

# URL
# baseurl:          "" # For Root Domain
baseurl:            ""
permalink:          /blogger/:year/:month/:day/:title/

# Markdown
markdown:           "redcarpet"
redcarpet:
  extensions:       ["no_intra_emphasis", "fenced_code_blocks", "disable_indented_code_blocks", "autolink", "strikethrough", "superscript", "tables"]

# Sass
sass:
  style:            :compressed
  sass_dir:         "/stylesheets/_primer"

# Break Point
excerpt_separator:  "<!--excerpt-->"

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
      comments:     "disqus"        # options: [google, disqus]
