# # # # # # # #
#   Akiicat   #
# # # # # # # #

# Basic
name:               "Akiicat"

# URL
# baseurl:          "" # For Root Domain
baseurl:            ""
permalink:          /blogger/:year/:month/:day/:title/

# Markdown
markdown:           "redcarpet"
redcarpet:
  extensions:       ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "tables"]

# Navigation
nav:
  - name:           "About"
    href:           "//gfjaru.github.io/about"
  - name:           "Download"
    href:           "//github.com/gfjaru/releases"

# Sass
sass:
  style:            :compressed
  sass_dir:         "/stylesheets/_primer"

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
      comments:     "disqus"        # options: [google, disqus]
  -
    scope:
      path:         "_posts/c:c++"
    values:
      category:     "C/C++"
  -
    scope:
      path:         "_posts/ruby_on_rails"
    values:
      category:     "Ruby on Rails"
  -
    scope:
      path:         "_posts/javascript"
    values:
      category:     "Javascript"
